# Parte 3: Cruce por ubigeo y análisis

## 3.1. Paso 1

Creen el archivo datos/ubigeos.csv con las columnas ubigeo y departamento.

Para ello, primero se va a importar pandas, para luego elaborar un dataframe con las columnas ubigeo y departamento. Por último, se guarda en un archivo CSV.

In [1]:
import pandas as pd

In [2]:
ubigeos = pd.DataFrame({
    "ubigeo": ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"],
    "departamento": ["Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca", "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad", "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco", "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali"]
})

# Se guarda el DataFrame en un archivo CSV
ubigeos.to_csv("datos/ubigeos.csv", index=False, encoding="utf-8-sig")
ubigeos

   ubigeo   departamento
0      01       Amazonas
1      02         Áncash
2      03       Apurímac
3      04       Arequipa
4      05       Ayacucho
5      06      Cajamarca
6      07         Callao
7      08          Cusco
8      09   Huancavelica
9      10        Huánuco
10     11            Ica
11     12          Junín
12     13    La Libertad
13     14     Lambayeque
14     15           Lima
15     16         Loreto
16     17  Madre de Dios
17     18       Moquegua
18     19          Pasco
19     20          Piura
20     21           Puno
21     22     San Martín
22     23          Tacna
23     24         Tumbes
24     25        Ucayali

## 3.2. Paso 2

**Enunciado**: Léanlo dos veces: una con pd.read_csv normal y otra con dtype={"ubigeo": str}. Muestren la diferencia y expliquen en una celda de texto por qué importa.

In [3]:
# Lectura del archivo ubigeos.csv, sin especificar el parámetro dtype

ubigeos_sin_dtype = pd.read_csv("datos/ubigeos.csv")
ubigeos_sin_dtype

    ubigeo   departamento
0        1       Amazonas
1        2         Áncash
2        3       Apurímac
3        4       Arequipa
4        5       Ayacucho
5        6      Cajamarca
6        7         Callao
7        8          Cusco
8        9   Huancavelica
9       10        Huánuco
10      11            Ica
11      12          Junín
12      13    La Libertad
13      14     Lambayeque
14      15           Lima
15      16         Loreto
16      17  Madre de Dios
17      18       Moquegua
18      19          Pasco
19      20          Piura
20      21           Puno
21      22     San Martín
22      23          Tacna
23      24         Tumbes
24      25        Ucayali

In [4]:
# Muestra el tipo de datos de cada columna
ubigeos_sin_dtype.dtypes

ubigeo           int64
departamento    object
dtype: object

In [5]:
# Lectura del archivo ubigeos.csv, especificando el parámetro dtype

ubigeos_con_dtype = pd.read_csv("datos/ubigeos.csv", dtype={"ubigeo": str})
ubigeos_con_dtype

   ubigeo   departamento
0      01       Amazonas
1      02         Áncash
2      03       Apurímac
3      04       Arequipa
4      05       Ayacucho
5      06      Cajamarca
6      07         Callao
7      08          Cusco
8      09   Huancavelica
9      10        Huánuco
10     11            Ica
11     12          Junín
12     13    La Libertad
13     14     Lambayeque
14     15           Lima
15     16         Loreto
16     17  Madre de Dios
17     18       Moquegua
18     19          Pasco
19     20          Piura
20     21           Puno
21     22     San Martín
22     23          Tacna
23     24         Tumbes
24     25        Ucayali

In [6]:
# Muestra el tipo de datos de cada columna
ubigeos_con_dtype.dtypes

ubigeo          object
departamento    object
dtype: object

El ubigeo del departamento es un código de 2 dígitos, lo cual está estandarizado por el INEI, por ello se debe respetar la estructura de 2 dígitos. Frente a ello, el parámetro dtype de pd.read_csv permite mantener esa estructura, por lo cual, se recomienda su uso para la lectura del archivo ubigeos.csv. Si no se usara, pandas lo reconocería como número y se perdería el 0 de los primeros 9 códigos de ubigeo. Además, cuando se requiera hacer un cruce de información con otras tablas, el ubigeo suele ser la columna llave para hacer el cruce, si no se respeta la estructura, saldrá error.